(cl:defpackage robot_soccer-srv
  (:use )
  (:export
   "COMMCENTER"
   "<COMMCENTER-REQUEST>"
   "COMMCENTER-REQUEST"
   "<COMMCENTER-RESPONSE>"
   "COMMCENTER-RESPONSE"
   "CURLOCS"
   "<CURLOCS-REQUEST>"
   "CURLOCS-REQUEST"
   "<CURLOCS-RESPONSE>"
   "CURLOCS-RESPONSE"
  ))

