(cl:in-package robot_soccer-msg)
(cl:export '(HEADER-VAL
          HEADER
          HOME1_X-VAL
          HOME1_X
          HOME1_Y-VAL
          HOME1_Y
          HOME1_THETA-VAL
          HOME1_THETA
          HOME2_X-VAL
          HOME2_X
          HOME2_Y-VAL
          HOME2_Y
          HOME2_THETA-VAL
          HOME2_THETA
          AWAY1_X-VAL
          AWAY1_X
          AWAY1_Y-VAL
          AWAY1_Y
          AWAY1_THETA-VAL
          AWAY1_THETA
          AWAY2_X-VAL
          AWAY2_X
          AWAY2_Y-VAL
          AWAY2_Y
          AWAY2_THETA-VAL
          AWAY2_THETA
          BALL_X-VAL
          BALL_X
          BALL_Y-VAL
          BALL_Y
          FIELD_WIDTH-VAL
          FIELD_WIDTH
          FIELD_HEIGHT-VAL
          FIELD_HEIGHT
))