// Generated by gencpp from file robot_soccer/commcenter.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_COMMCENTER_H
#define ROBOT_SOCCER_MESSAGE_COMMCENTER_H

#include <ros/service_traits.h>


#include <robot_soccer/commcenterRequest.h>
#include <robot_soccer/commcenterResponse.h>


namespace robot_soccer
{

struct commcenter
{

typedef commcenterRequest Request;
typedef commcenterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct commcenter
} // namespace robot_soccer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_soccer::commcenter > {
  static const char* value()
  {
    return "f20d8de9800e6b15bcaa4586b124e5e2";
  }

  static const char* value(const ::robot_soccer::commcenter&) { return value(); }
};

template<>
struct DataType< ::robot_soccer::commcenter > {
  static const char* value()
  {
    return "robot_soccer/commcenter";
  }

  static const char* value(const ::robot_soccer::commcenter&) { return value(); }
};


// service_traits::MD5Sum< ::robot_soccer::commcenterRequest> should match 
// service_traits::MD5Sum< ::robot_soccer::commcenter > 
template<>
struct MD5Sum< ::robot_soccer::commcenterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::commcenter >::value();
  }
  static const char* value(const ::robot_soccer::commcenterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::commcenterRequest> should match 
// service_traits::DataType< ::robot_soccer::commcenter > 
template<>
struct DataType< ::robot_soccer::commcenterRequest>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::commcenter >::value();
  }
  static const char* value(const ::robot_soccer::commcenterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_soccer::commcenterResponse> should match 
// service_traits::MD5Sum< ::robot_soccer::commcenter > 
template<>
struct MD5Sum< ::robot_soccer::commcenterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::commcenter >::value();
  }
  static const char* value(const ::robot_soccer::commcenterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::commcenterResponse> should match 
// service_traits::DataType< ::robot_soccer::commcenter > 
template<>
struct DataType< ::robot_soccer::commcenterResponse>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::commcenter >::value();
  }
  static const char* value(const ::robot_soccer::commcenterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_COMMCENTER_H
