// Generated by gencpp from file robot_soccer/commcenterRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_COMMCENTERREQUEST_H
#define ROBOT_SOCCER_MESSAGE_COMMCENTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_soccer
{
template <class ContainerAllocator>
struct commcenterRequest_
{
  typedef commcenterRequest_<ContainerAllocator> Type;

  commcenterRequest_()
    : comm(0)  {
    }
  commcenterRequest_(const ContainerAllocator& _alloc)
    : comm(0)  {
    }



   typedef int32_t _comm_type;
  _comm_type comm;




  typedef boost::shared_ptr< ::robot_soccer::commcenterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_soccer::commcenterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct commcenterRequest_

typedef ::robot_soccer::commcenterRequest_<std::allocator<void> > commcenterRequest;

typedef boost::shared_ptr< ::robot_soccer::commcenterRequest > commcenterRequestPtr;
typedef boost::shared_ptr< ::robot_soccer::commcenterRequest const> commcenterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_soccer::commcenterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_soccer::commcenterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_soccer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'robot_soccer': ['/home/ecestudent/catkin_ws/src/robot_soccer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::commcenterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::commcenterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::commcenterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f20d8de9800e6b15bcaa4586b124e5e2";
  }

  static const char* value(const ::robot_soccer::commcenterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf20d8de9800e6b15ULL;
  static const uint64_t static_value2 = 0xbcaa4586b124e5e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_soccer/commcenterRequest";
  }

  static const char* value(const ::robot_soccer::commcenterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 comm\n\
";
  }

  static const char* value(const ::robot_soccer::commcenterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.comm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct commcenterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_soccer::commcenterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_soccer::commcenterRequest_<ContainerAllocator>& v)
  {
    s << indent << "comm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.comm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_COMMCENTERREQUEST_H
