// Generated by gencpp from file robot_soccer/commandsent.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_COMMANDSENT_H
#define ROBOT_SOCCER_MESSAGE_COMMANDSENT_H

#include <ros/service_traits.h>


#include <robot_soccer/commandsentRequest.h>
#include <robot_soccer/commandsentResponse.h>


namespace robot_soccer
{

struct commandsent
{

typedef commandsentRequest Request;
typedef commandsentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct commandsent
} // namespace robot_soccer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_soccer::commandsent > {
  static const char* value()
  {
    return "2090a5a3e1241f8cc8576da8a833f62d";
  }

  static const char* value(const ::robot_soccer::commandsent&) { return value(); }
};

template<>
struct DataType< ::robot_soccer::commandsent > {
  static const char* value()
  {
    return "robot_soccer/commandsent";
  }

  static const char* value(const ::robot_soccer::commandsent&) { return value(); }
};


// service_traits::MD5Sum< ::robot_soccer::commandsentRequest> should match 
// service_traits::MD5Sum< ::robot_soccer::commandsent > 
template<>
struct MD5Sum< ::robot_soccer::commandsentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::commandsent >::value();
  }
  static const char* value(const ::robot_soccer::commandsentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::commandsentRequest> should match 
// service_traits::DataType< ::robot_soccer::commandsent > 
template<>
struct DataType< ::robot_soccer::commandsentRequest>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::commandsent >::value();
  }
  static const char* value(const ::robot_soccer::commandsentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_soccer::commandsentResponse> should match 
// service_traits::MD5Sum< ::robot_soccer::commandsent > 
template<>
struct MD5Sum< ::robot_soccer::commandsentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::commandsent >::value();
  }
  static const char* value(const ::robot_soccer::commandsentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::commandsentResponse> should match 
// service_traits::DataType< ::robot_soccer::commandsent > 
template<>
struct DataType< ::robot_soccer::commandsentResponse>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::commandsent >::value();
  }
  static const char* value(const ::robot_soccer::commandsentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_COMMANDSENT_H
