// Generated by gencpp from file robot_soccer/curlocsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_CURLOCSRESPONSE_H
#define ROBOT_SOCCER_MESSAGE_CURLOCSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_soccer
{
template <class ContainerAllocator>
struct curlocsResponse_
{
  typedef curlocsResponse_<ContainerAllocator> Type;

  curlocsResponse_()
    : pickle()  {
    }
  curlocsResponse_(const ContainerAllocator& _alloc)
    : pickle(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pickle_type;
  _pickle_type pickle;




  typedef boost::shared_ptr< ::robot_soccer::curlocsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_soccer::curlocsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct curlocsResponse_

typedef ::robot_soccer::curlocsResponse_<std::allocator<void> > curlocsResponse;

typedef boost::shared_ptr< ::robot_soccer::curlocsResponse > curlocsResponsePtr;
typedef boost::shared_ptr< ::robot_soccer::curlocsResponse const> curlocsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_soccer::curlocsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_soccer::curlocsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_soccer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'robot_soccer': ['/home/ecestudent/catkin_ws/src/robot_soccer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::curlocsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::curlocsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::curlocsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c8e4620cde9c3b16d1cfbdddb8c721c";
  }

  static const char* value(const ::robot_soccer::curlocsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c8e4620cde9c3b1ULL;
  static const uint64_t static_value2 = 0x6d1cfbdddb8c721cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_soccer/curlocsResponse";
  }

  static const char* value(const ::robot_soccer::curlocsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pickle\n\
";
  }

  static const char* value(const ::robot_soccer::curlocsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pickle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct curlocsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_soccer::curlocsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_soccer::curlocsResponse_<ContainerAllocator>& v)
  {
    s << indent << "pickle: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pickle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_CURLOCSRESPONSE_H
